name: lint
on: 
  pull_request:
    types: [opened, reopened]
env:
  RUSTFLAGS: "-Dwarnings"
jobs:
  clippy-lint:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Run Clippy
        run: |
          cd router
          cargo clippy
