name: lint
on: 
  pull_request:
    types: [opened, reopened]
jobs:
  npm-eslint:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - run: |
          cd coffee-project
          npm init @eslint/config
          ./node_modules/.bin/eslint .
