name: test
on: 
  pull_request:
    types: [opened, reopened]
jobs:
  npm_test_scripts:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '14.x'
      - run: cd coffee-project
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
