name: test
on: 
  pull_request:
    types: [opened, reopened]
jobs:
  npm_test_scripts:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - run: |
          cd coffee-project
          npm ci
          npm run build --if-present
          npm test
